# Generated by Django 5.1.4 on 2025-01-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок статьи"),
                ),
                (
                    "content",
                    models.TextField(max_length=1000, verbose_name="Текст статьи"),
                ),
                ("preview", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publish_attribute",
                    models.BooleanField(verbose_name="Признак публикации"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(verbose_name="Количество просмотров"),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["title"],
            },
        ),
    ]
