# Generated by Django 5.1.4 on 2025-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="publish_attribute",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
