# Generated by Django 5.1.4 on 2025-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_publish_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="Изображение"
            ),
        ),
    ]
