# Generated by Django 5.1.4 on 2025-01-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=150, verbose_name="Категория"),
                ),
                ("category_description", models.TextField()),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категория",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="Наименование"),
                ),
                (
                    "product_description",
                    models.TextField(max_length=200, verbose_name="Описание"),
                ),
                ("product_image", models.ImageField(upload_to="")),
                ("product_price", models.IntegerField()),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["product_name", "category_name"],
            },
        ),
    ]
