# Generated by Django 5.1.4 on 2025-01-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория продуктов",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(verbose_name="Стоимость"),
        ),
    ]
