# Generated by Django 5.1.4 on 2025-01-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/", verbose_name="Изображение"
            ),
        ),
    ]
