# Generated by Django 5.1.4 on 2025-02-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name", "category_name"],
                "permissions": [("can_unpublish_product", "can unpublish product")],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
