# Generated by Django 5.1.4 on 2025-02-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name", "category_name"],
                "permissions": [
                    ("can_unpublish_product", "can unpublish product"),
                    ("can_delete_product", "can delete product"),
                ],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
